version: 2

sources:
  - name: raw_pay
    database: eco-rune-459817-m9
    schema: raw_pay
    tables:
      - name: ordini
      - name: transazioni
      - name: abbonamenti
      - name: rinnovi
      - name: utenti
      - name: piani
      - name: metodi
      - name: coupon